version: '3'

services:
  database:
    container_name: docker_data_base
    build: ./DataBase
    ports:
      - 5433:5432
  backend:
    container_name: docker_back_end
    build: ./ExpressBases
    ports:
      - 5000:5000
  frontend:
    container_name: docker_front_end
    build: ./ReactBases
    ports:
      - 3000:3000
      